### ISSUE TITLE
[FE] QR 코드 기능 구체화

### ISSUE THREAD

**Issue by harvartz** [kinopioB/EatGo-Frontend#12]
## Feature Description
- 레이아웃 구성
- QR 생성 시, 파라미터 값 넘기기

## Todo list

- [x] 커스텀 레이아웃 구성
- [x] QR 생성 시, 파라미터 값 넘기기
- [x] QR 생성 페이지에서 뒤로가기 ActionBar 만들기
- [x] 스캔 했을 시, 리뷰 아이디 생성 및 페이지 URL 넘기기
- [ ] Retrofit 사용해서, 해당 storeId와 review내용이 통신되는지 확인
