### ISSUE TITLE
[FE] Toolbar, 화면 연결하기

### ISSUE THREAD

**Issue by harvartz** [kinopioB/EatGo-Frontend#22]
## Feature Description
- Toolbar 만들기
- 화면 연결하기
- QR 인식 후, Activity 옮기기
- MyPage 안드로이드 구현

## Todo list

- [x] Toolbar 만들기 - 화면마다 동적처리
- [ ] 화면 연결하기
- [x] QR 인식 후, Activity 옮기기
- [x] MyPage 안드로이드 구현
