### ISSUE TITLE
[FE] 가게 등록 페이지 UI 수정 및 이미지 업로드 & 데이터 요청 연결

### ISSUE THREAD

**Issue by SeungJooKim** [kinopioB/EatGo-Frontend#23]
## Feature Description
- 가게 등록 페이지 UI 미완성 부분 수정
- 가게 등록 API 호출 ( retrofit  사용 )
- 가게 등록 이미지 업로드 

## Todo list

- [ ] 가게 등록 페이지 recycler view ui 수정
- [ ] 가게 등록 다중 이미지 업로드 
- [ ] 가게 등록 Rest API 호출 
- [ ] 페이지 연결
