### ISSUE TITLE
[FE] 최근 오픈 / 인기 가게 페이지 구현

### ISSUE THREAD

**Issue by SeungJooKim** [kinopioB/EatGo-Frontend#31]
## Feature Description
-  최근 오픈 / 인기 가게 페이지 구현

## Todo list

- [ ]  최근 오픈 / 인기 가게 페이지 UI 구현
- [x] 데이터 불러와서 띄우기
- [ ] detail 페이지로 넘어갈 수 있게 설정하기
