### ISSUE TITLE
[FE] 가게 등록 페이지  구현

### ISSUE THREAD

**Issue by SeungJooKim** [kinopioB/EatGo-Frontend#33]
## Feature Description
- 가게 등록 페이지 구현 

## Todo list

- [x] 가게 상세 설명란 추가
- [x] 가게 이미지 추가 (갤러리 연동)
- [x] 가게 태그 입력 기능 주가
- [x] 페이지 UI 전반 수정
