### ISSUE TITLE
[FE] mypage 가게, toolbar 연결

### ISSUE THREAD

**Issue by harvartz** [kinopioB/EatGo-Frontend#37]
## Feature Description
- 

## Todo list

- [x] 등록 페이지 Action Bar 연결
- [x] 사용자가 QR 찍을 카메라 위치 설정하고 연결
- [x] 관리자 MyPage 리뷰 QR 연결
- [x] 관리자 MyPage 위치 받아서 영업 등록 / 종료 되는 지 확인
- [ ] 사용자 MyPage → 일단 맨 나중 ( 보류 )
