### ISSUE TITLE
[FE] 프론트 버그 수정 및 데이터 연결 추가 

### ISSUE THREAD

**Issue by SeungJooKim** [kinopioB/EatGo-Frontend#62]
## Feature Description
- 데이터 연결 및 프론트 버그 수정

## Todo list

- [x] 상세 페이지 가게 info 정보 넘어오는 지 확인
- [ ] 관리자 페이지 태그 띄우기 / 영업 여부에 따라 버튼 영업중 버튼 다르게 띄우기
- [ ] 관리자 페이지 리뷰 item 수정하기
- [x] 가게 상세 페이지 영업일 정보 띄우기
- [x] 상세 페이지 메뉴 info 정보 띄워야함 ( 데이터 전송되오는 값이 null 같음 -> 백엔드도 수정 )
- [ ] 로딩바 연결하기 ( 상세 페이지 띄울 때 )
- [ ] 북마크 추가하기
